name: Deploy Application

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Pobierz kod z repozytorium
              uses: actions/checkout@v3

            - name: Skonfiguruj Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Instalacja zależności w backendzie
              run: |
                  cd backend
                  npm install

            - name: Wdróż backend na Render/Heroku (jeśli używasz)
              run: |
                  cd backend
                  npm run deploy  # zmień to na komendę wymaganą do wdrożenia

            - name: Instalacja zależności w frontendzie
              run: |
                  cd frontend
                  npm install
                  npm run build

            - name: Wdróż frontend na GitHub Pages/Vercel/Netlify
              run: |
                  cd frontend
                  npm run deploy  # zmień na odpowiednią komendę
